spring.application.name=demo
spring.security.user.name=admin
spring.security.user.password=admin123

spring.datasource.url=jdbc:postgresql://localhost:5432/security
spring.datasource.username=postgres
spring.datasource.password=1908
# spring.datasource.driver-class-name=org.postgresql.Driver 

# Исправлено: режим управления схемами БД (теперь таблицы создадутся сами)
spring.jpa.hibernate.ddl-auto=update
# Показывать SQL-запросы в консоли
# spring.jpa.show-sql=true